services:
  api:
    build: .
    container_name: gopportunities-api
    env_file:
      - .env
    environment:
      DB_PATH: /app/db/main.db
    ports:
      - "8081:8081"
    volumes:
      - ./db:/app/db
    restart: unless-stopped
